# fluttergen => fiabilisation des assets
# flutter packages pub run build_runner build --delete-conflicting-outputs
name: com_mcb_jobs_in_retail_from_shopit
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  badges: ^2.0.3
  cloud_firestore: ^4.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  firebase_storage: ^11.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  pay: ^1.0.10
  rating_dialog: ^2.0.4
  uuid: ^3.0.6
  logger: ^1.1.0
  another_flushbar: ^1.12.29
  responsive_sizer: ^3.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  validators: ^3.0.0 # validation email
dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:

  flutter_test:
    sdk: flutter
  freezed: ^2.3.0
  json_serializable: ^6.5.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/categories/
    - assets/images/
  fonts:
    - family: Syncopate
      fonts:
        - asset: assets/fonts/Syncopate-Regular.ttf
        - asset: assets/fonts/Syncopate-Bold.ttf

